version: '3.7'

services:
   nexthealth-application:
     build:
       context: .
       dockerfile: Dockerfile 
     ports:
       - 8080:8080
     restart: always
     environment:
        KAFKA_TOPIC : "${KAFKA_TOPIC}"
        KAFKA_BOOTSTRAP_SERVER : "${KAFKA_BOOTSTRAP_SERVER}"
        KAFKA_ADMIN_USER : "${KAFKA_ADMIN_USER}"
        KAFKA_ADMIN_PASSWORD : "${KAFKA_ADMIN_PASSWORD}"
        POSTGRES_URL : "${POSTGRES_URL}"
        POSTGRES_USERNAME : "${POSTGRES_USERNAME}"
        POSTGRES_PASSWORD : "${POSTGRES_PASSWORD}"
        SPRING_PROFILES_ACTIVE : "${SPRING_PROFILES_ACTIVE}"
