version: '2.4'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: notificationService
      MONGO_INITDB_ROOT_PASSWORD: notificationService
    volumes:
      - mongodb:/usr/share/mongodb/data
    ports:
      - '3011:27017'

volumes:
  mongodb:
    driver: local
