export const enum SMSErrorCode {
    AUTH_FAILURE = 'SMSERR_001',
    MISSING_AUTH_PARAM = 'SMSERR_002',
    INVALID_PARAM_FORMAT = 'SMSERR_003',
    DUPLICATE_MESSAGE = 'SMSERR_004',
    PAGE_LIMIT_EXCEEDED = 'SMSERR_005',
    TOO_MANY_REQUESTS = 'SMSERR_006',
    INVALID_ENCODING = 'SMSERR_007',
    INCOMPATIBLE_API_VERSION = 'SMSERR_008',

    RECEPIENT_MISSING = 'SMSERR_051',
    RECEPIENT_FORMAT_INVALID = 'SMSERR_052',
    RECEPIENT_INVALID = 'SMSERR_053',
    RECEPIENT_TOO_MANY_ENTRIES = 'SMSERR_054',

    MESSAGE_BODY_TOO_LONG = 'SMSERR_101',
    MESSAGE_BODY_INVALID = 'SMSERR_102',
    MESSAGE_BODY_MISSING = 'SMSERR_103',
    MESSAGE_BODY_EMPTY = 'SMSERR_104',

    SENDER_FORMAT_INVALID = 'SMSERR_151',
    SENDER_APPSID_MISMATCH = 'SMSERR_152',
    SENDER_INVALID = 'SMSERR_153',

    CORRELATION_ID_FORMAT_INVALID = 'SMSERR_201',

    GENERIC_ERROR = 'SMSERR_501',
    REQUEST_ERROR = 'SMSERR_999',
}
