export enum Environment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}

export enum ERROR_CODES {
  MISSING_TEMPLATE_CODE = 'MISSING_TEMPLATE_CODE',
  MISSING_SMS_RECIPIENT = 'MISSING_SMS_RECIPIENT',
  TEMPLATE_PARAMS_MISSING = 'TEMPLATE_PARAMS_MISSING',
  TEMPLATE_TYPE_MISSING = 'TEMPLATE_TYPE_MISSING',
  TEMPLATE_LANGUAGE_MISSING = 'TEMPLATE_LANGUAGE_MISSING',
}
