
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-poc
    username: postgres
    password: postgres
#graphql:
#  servlet:
#    cors-enabled: true
#    cors:
#      allowed-origins: ${CORS_ALLOWED_HOSTS}
#      allowed-methods: GET, HEAD, POST, OPTIONS
#      allow-credentials: true
#      allowed-headers: "*"
graphiql:
  enabled: true
server:
  port: 8077
