module.exports = {
  mockOrderWithPayment: {
    id: 1,
    schedule: "2022-09-30T09:30:00.000Z",
    amount: 222,
    currency: "AED",
    status: "Insurance Approved",
    createdAt: "2022-09-29T11:50:48.659Z",
    updatedAt: "2022-10-24T11:34:08.250Z",
    prescription: {
      id: 1,
    },
    payment: {
      id: 21,
      maskedCardNumber: null,
      amount: 222,
      currency: "AED",
      status: "Payment Method Required",
      providerPaymentId: "pi_3LwOuyI3Fb4xUkyy1QTkEfcq",
      providerMetadata: {
        id: "pi_3LwOuyI3Fb4xUkyy1QTkEfcq",
        amount: 222,
        object: "payment_intent",
        review: null,
        source: null,
        status: "requires_payment_method",
        charges: [Object],
        created: 1666611248,
        invoice: null,
        currency: "aed",
        customer: null,
        livemode: false,
        metadata: [Object],
        shipping: null,
        processing: null,
        application: null,
        canceled_at: null,
        description: null,
        next_action: null,
        on_behalf_of: null,
        client_secret:
          "pi_3LwOuyI3Fb4xUkyy1QTkEfcq_secret_qhEiiiKIVOWPFtdtmmY54rtif",
        receipt_email: null,
        transfer_data: null,
        amount_details: [Object],
        capture_method: "automatic",
        payment_method: null,
        transfer_group: null,
        amount_received: 0,
        amount_capturable: 0,
        last_payment_error: null,
        setup_future_usage: null,
        cancellation_reason: null,
        confirmation_method: "automatic",
        payment_method_types: [Array],
        statement_descriptor: null,
        application_fee_amount: null,
        payment_method_options: [Object],
        automatic_payment_methods: [Object],
        statement_descriptor_suffix: null,
      },
      correlationId: "16",
      createdAt: "2022-10-24T11:34:08.285Z",
      updatedAt: "2022-10-24T11:34:08.285Z",
      paymentType: null,
      history: [
        {
          id: 39,
          type: "Payment Method Required",
          timeStamp: "2022-11-01T12:32:27.022Z",
          metadata: [Object],
          eventSource: null,
        },
      ],
    },
    patient: {
      id: 16,
      username: "971529029931",
      email: "1@gmail.com",
      provider: "local",
      password: "$2a$10$lOV/0atcXrg9vU5PZ8TVsOXJ2o5vAKC6BXKGST65mEi6PGK9yDSbS",
      resetPasswordToken: null,
      confirmationToken: null,
      confirmed: true,
      blocked: false,
      createdAt: "2022-09-02T02:42:28.031Z",
      updatedAt: "2022-10-17T10:15:02.495Z",
      passwordExpiresAt: "2022-10-17T10:19:45.733Z",
      firstName: "shanawaj",
      middleName: null,
      lastName: "khan",
      mobileNumber: null,
      emiratesId: "1984-2004-1112222-6",
      reminderFrequency: 30,
      passwordGeneratedAt: "2022-10-17T10:14:45.733Z",
      maxUnsuccessfulLoginCount: 0,
      lastUnsuccessfulLoginTime: "2022-10-10T08:02:47.626Z",
    },
  },

  mockOrderWithOutPayment: {
    id: 1,
    schedule: "2022-09-30T09:30:00.000Z",
    amount: 222,
    currency: "AED",
    status: "Insurance Approved",
    createdAt: "2022-09-29T11:50:48.659Z",
    updatedAt: "2022-10-24T08:52:53.742Z",
    payment: null,
    prescription: {
      id: 1,
    },
    patient: {
      id: 16,
      username: "971529029931",
      email: "1@gmail.com",
      provider: "local",
      password: "$2a$10$lOV/0atcXrg9vU5PZ8TVsOXJ2o5vAKC6BXKGST65mEi6PGK9yDSbS",
      resetPasswordToken: null,
      confirmationToken: null,
      confirmed: true,
      blocked: false,
      createdAt: "2022-09-02T02:42:28.031Z",
      updatedAt: "2022-10-17T10:15:02.495Z",
      passwordExpiresAt: "2022-10-17T10:19:45.733Z",
      firstName: "shanawaj",
      middleName: null,
      lastName: "khan",
      mobileNumber: null,
      emiratesId: "1984-2004-1112222-6",
      reminderFrequency: 30,
      passwordGeneratedAt: "2022-10-17T10:14:45.733Z",
      maxUnsuccessfulLoginCount: 0,
      lastUnsuccessfulLoginTime: "2022-10-10T08:02:47.626Z",
    },
  },
  mockCtx: {
    request: {
      body: {
        orderId: 1,
      },
    },
  },
  mockPayment: {
    id: 30,
    maskedCardNumber: null,
    amount: 32.25,
    currency: "AED",
    status: "requires_payment_method",
    providerPaymentId: "pi_3LzJdnI3Fb4xUkyy1OQBwwVD",
    providerMetadata: {
      id: "pi_3LzJdnI3Fb4xUkyy1OQBwwVD",
      amount: 3225,
      object: "payment_intent",
      review: null,
      source: null,
      status: "requires_payment_method",
      charges: {
        url: "/v1/charges?payment_intent=pi_3LzJdnI3Fb4xUkyy1OQBwwVD",
        data: [],
        object: "list",
        has_more: false,
        total_count: 0,
      },
      created: 1667305947,
      invoice: null,
      currency: "aed",
      customer: null,
      livemode: false,
      metadata: { orderId: "1", patientId: "16", prescriptionId: "1" },
      shipping: null,
      processing: null,
      application: null,
      canceled_at: null,
      description: null,
      next_action: null,
      on_behalf_of: null,
      client_secret:
        "pi_3LzJdnI3Fb4xUkyy1OQBwwVD_secret_x0o0uzZLdxsCJplqYP4VXGPx3",
      receipt_email: null,
      transfer_data: null,
      amount_details: { tip: {} },
      capture_method: "automatic",
      payment_method: null,
      transfer_group: null,
      amount_received: 0,
      amount_capturable: 0,
      last_payment_error: null,
      setup_future_usage: null,
      cancellation_reason: null,
      confirmation_method: "automatic",
      payment_method_types: ["card"],
      statement_descriptor: null,
      application_fee_amount: null,
      payment_method_options: { card: [Object] },
      automatic_payment_methods: { enabled: true },
      statement_descriptor_suffix: null,
    },
    correlationId: "16",
    createdAt: "2022-11-01T12:32:27.092Z",
    updatedAt: "2022-11-01T12:32:27.092Z",
    paymentType: null,
    order: {
      id: 1,
      schedule: "2022-09-30T09:30:00.000Z",
      amount: 32.25,
      currency: "AED",
      status: "Require Payment",
      createdAt: "2022-09-29T11:50:48.659Z",
      updatedAt: "2022-11-01T12:32:27.028Z",
    },
    patient: {
      id: 16,
      username: "971529029932",
      email: "1@gmail.com",
      provider: "local",
      password: "$2a$10$f3SfHeZNmSy4vT/YwXy.GuobceP9ZUwvWcgTR3zHDrtgLNcrtKh3i",
      resetPasswordToken: null,
      confirmationToken: null,
      confirmed: true,
      blocked: false,
      createdAt: "2022-09-02T02:42:28.031Z",
      updatedAt: "2022-11-01T07:56:05.516Z",
      passwordExpiresAt: "2022-10-31T06:34:46.238Z",
      firstName: "shanawaj",
      middleName: null,
      lastName: "khan",
      mobileNumber: null,
      emiratesId: "1984-2004-1112222-6",
      reminderFrequency: 30,
      passwordGeneratedAt: "2022-10-31T06:29:46.238Z",
      maxUnsuccessfulLoginCount: 0,
      lastUnsuccessfulLoginTime: "2022-10-10T08:02:47.626Z",
    },
    history: [
      {
        id: 39,
        type: "Payment Method Required",
        timeStamp: "2022-11-01T12:32:27.022Z",
        metadata: [Object],
        eventSource: null,
      },
    ],
  },

  mockPaymentMethod: {
    id: "pm_1LxUeZI3Fb4xUkyyST0sAijk",
    object: "payment_method",
    billing_details: {
      address: {
        city: null,
        country: "AE",
        line1: null,
        line2: null,
        postal_code: null,
        state: null,
      },
      email: null,
      name: null,
      phone: null,
    },
    card: {
      brand: "visa",
      checks: {
        address_line1_check: null,
        address_postal_code_check: null,
        cvc_check: "pass",
      },
      country: "US",
      exp_month: 2,
      exp_year: 2033,
      fingerprint: "xskb6Q5VBYKF9eW2",
      funding: "credit",
      generated_from: null,
      last4: "4242",
      networks: { available: [Array], preferred: null },
      three_d_secure_usage: { supported: true },
      wallet: null,
    },
    created: 1666871624,
    customer: null,
    livemode: false,
    metadata: {},
    type: "card",
  },
  mockPaymentMethodWithWallet: {
    id: "pm_1LxUeZI3Fb4xUkyyST0sAijk",
    object: "payment_method",
    billing_details: {
      address: {
        city: null,
        country: "AE",
        line1: null,
        line2: null,
        postal_code: null,
        state: null,
      },
      email: null,
      name: null,
      phone: null,
    },
    card: {
      brand: "visa",
      checks: {
        address_line1_check: null,
        address_postal_code_check: null,
        cvc_check: "pass",
      },
      country: "US",
      exp_month: 2,
      exp_year: 2033,
      fingerprint: "xskb6Q5VBYKF9eW2",
      funding: "credit",
      generated_from: null,
      last4: "4242",
      networks: { available: [Array], preferred: null },
      three_d_secure_usage: { supported: true },
      wallet: {
        type: "apple_pay",
      },
    },
    created: 1666871624,
    customer: null,
    livemode: false,
    metadata: {},
    type: "card",
  },
  mockPaymentIntent: {
    id: "pi_3LxUbYI3Fb4xUkyy0DkL9xKk",
    object: "payment_intent",
    amount: 1000,
    amount_capturable: 0,
    amount_details: { tip: {} },
    amount_received: 1000,
    application: null,
    application_fee_amount: null,
    automatic_payment_methods: { enabled: true },
    canceled_at: null,
    cancellation_reason: null,
    capture_method: "automatic",
    charges: {
      object: "list",
      data: [[Object]],
      has_more: false,
      total_count: 1,
      url: "/v1/charges?payment_intent=pi_3LxUbYI3Fb4xUkyy0DkL9xKk",
    },
    client_secret:
      "pi_3LxUbYI3Fb4xUkyy0DkL9xKk_secret_cuWetmUfBrGgGtnXLP3AgcMKV",
    confirmation_method: "automatic",
    created: 1666871436,
    currency: "aed",
    customer: null,
    description: null,
    invoice: null,
    last_payment_error: null,
    livemode: false,
    metadata: { bookingId: "This is the booking id" },
    next_action: null,
    on_behalf_of: null,
    payment_method: "pm_1LxUeZI3Fb4xUkyyST0sAijk",
    payment_method_options: {
      card: {
        installments: null,
        mandate_options: null,
        network: null,
        request_three_d_secure: "automatic",
      },
    },
    payment_method_types: ["card"],
    processing: null,
    receipt_email: null,
    review: null,
    setup_future_usage: null,
    shipping: null,
    source: null,
    statement_descriptor: null,
    statement_descriptor_suffix: null,
    status: "succeeded",
    transfer_data: null,
    transfer_group: null,
  },
  mockPaymentDetails: {
    id: "pi_3LzJdnI3Fb4xUkyy1OQBwwVD",
    object: "payment_intent",
    amount: 3225,
    amount_capturable: 0,
    amount_details: { tip: {} },
    amount_received: 0,
    application: null,
    application_fee_amount: null,
    automatic_payment_methods: { enabled: true },
    canceled_at: null,
    cancellation_reason: null,
    capture_method: "automatic",
    charges: {
      object: "list",
      data: [],
      has_more: false,
      total_count: 0,
      url: "/v1/charges?payment_intent=pi_3LzJdnI3Fb4xUkyy1OQBwwVD",
    },
    client_secret:
      "pi_3LzJdnI3Fb4xUkyy1OQBwwVD_secret_x0o0uzZLdxsCJplqYP4VXGPx3",
    confirmation_method: "automatic",
    created: 1667305947,
    currency: "aed",
    customer: null,
    description: null,
    invoice: null,
    last_payment_error: null,
    livemode: false,
    metadata: { orderId: "1", patientId: "16", prescriptionId: "1" },
    next_action: null,
    on_behalf_of: null,
    payment_method: null,
    payment_method_options: {
      card: {
        installments: null,
        mandate_options: null,
        network: null,
        request_three_d_secure: "automatic",
      },
    },
    payment_method_types: ["card"],
    processing: null,
    receipt_email: null,
    review: null,
    setup_future_usage: null,
    shipping: null,
    source: null,
    statement_descriptor: null,
    statement_descriptor_suffix: null,
    status: "requires_payment_method",
    transfer_data: null,
    transfer_group: null,
  },
  mockCtxWithLoggedInUser: {
    params: {
      orderID: "1",
    },
    state: {
      user: {
        id: 16,
      },
    },
    request:{
      body:{
        paymentMethod:"default"
      }
    }
  },
  mockCtxWithNotLoggedInUser: {
    params: {
      orderID: "1",
    },
    state: {
      user: {
        id: 17,
      },
    },
    request:{
      body:{
        paymentMethod:"default"
      }
    },
  },
  mockCtxForCashOnDelivery: {
    params: {
      orderID: "1",
    },
    state: {
      user: {
        id: 16,
      },
    },
    request:{
      body:{
        paymentMethod:"Cash On Delivery"
      }
    }
  },
};
