#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx next lint --fix
# yarn test
# git add -A .
echo '🏗️👷 This is not a drill, we are about to do pre-check for the commits'
echo '🚨 '
echo '🚨 Prettier'
echo '🚨 Eslint'
echo '🚨 Types'
echo '🚨 Tests And Coverage'
echo '🚨 Stagging'
echo '🚨 Build'
echo '🚨 '


# Check Prettier standards
yarn run check-format ||
(
    echo '❌ Please style your code more appropriately; - it is currently raw. Make it prettier.
            Prettier Check Failed. Run yarn run format, add changes and try commit again.';
    false;
)
echo ' ✅ Prettier Passed '


# Check ESLint Standards
yarn run check-lint ||
(
        echo '❌ Before committing, kindly ensure that all eslint-related issues have been fixed.  
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)
echo ' ✅ ESLint Passed'


# Check tsconfig standards
yarn run check-types ||
(
    echo '❌ Failed Type check. 
            Are you seriously trying to write that? Make the changes required above.'
    false;
)
echo ' ✅ Types check Passed'


# Check tsconfig standards
yarn run test || 
(
    echo '❌ Failed Test check. 
            Make sure all the test and the coverage passes.'
    false;
)
echo ' ✅ Running Tests'

git add .

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'