spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      auto-index-creation: true
  kafka:
    enabled: true
    template:
      default-topic: pharmacies
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_ADMIN_USER}  password=${KAFKA_ADMIN_PASSWORD};

    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: pharmacies-service
      properties:
        spring.json.value.default.type: com.albatha.nexthealth.domain.Event
        spring.json.trusted.packages: com.albatha.nexthealth.*
        spring.json.use.type.headers: false

    admin:
      properties:
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVER}
graphql:
  servlet:
    cors-enabled: false
graphiql:
  enabled: false

