apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "autofix"
  description: "Autofix Web application"
  annotations:
    github.com/project-slug: albathanext/automotive/autofix-web
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "albathanext"
