version: '3.7'

services:
  main:
    container_name: supergeneral_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - webnet
    volumes:
      - mongodb-data:/data/db'
    ports:
      - 27017:27017
    command: mongod

networks:
  webnet:
volumes:
  mongodb-data:
